name: smart-video-processor
version: 1.1.0
summary: 'Automated video processing. Re-Organize, Re-encode, adds metadata and image.'
description: 'This small application is a frontend for FFmpeg and MKVToolNix. Its purpose is to help process and encode your DVD or Blu-ray backups.'

license: GPL-3.0+
icon: resources/icon.png

base: core24
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo

apps:
  smart-video-processor:
    command: smart-video-processor-launcher --no-sandbox
    extensions:
      - gnome
    plugs:
      - network
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  smart-video-processor:
    plugin: nil
    source: .
    override-build: |
      npm install electron electron-builder
      npx electron-builder --dir --linux --x64
      cp -rv ./dist/linux-unpacked $SNAPCRAFT_PART_INSTALL/smart-video-processor
      chmod a+rx $SNAPCRAFT_PART_INSTALL/smart-video-processor
      cp ./snap/bin/smart-video-processor-launcher $SNAPCRAFT_PART_INSTALL/
    build-snaps:
      - node/22/stable
    build-packages:
      - unzip
    stage-packages:
      - ffmpeg
      - mkvtoolnix
      - libproxy1v5
      - glib-networking
      - libblas3
      - liblapack3
    organize:
      usr/lib/*-linux-gnu/blas/*: usr/lib/
      usr/lib/*-linux-gnu/lapack/*.so*: usr/lib/

plugs:
  shared-memory:
    private: true
  home:
    interface: home
