name: package linux

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      discussions: write
      deployments: write
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        node-version: [24.x]

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Force Node.js 24 for all actions

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
        with:
          lfs: false

      - name: Fetch LFS objects
        run: |
          git lfs install
          git lfs pull

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: prepare-package
        run: npm run prepare-package

      - name: package arm64
        if: runner.arch == 'ARM64'
        run: npm run package -- --arm64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: package x64
        if: runner.arch == 'X64'
        run: npm run package -- --x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build linux snap
        uses: snapcore/action-build@v1
        id: build
        with:
          snapcraft-channel: '8.x'

      - name: publish to snap store
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable
