name: package win32

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      discussions: write
      deployments: write
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2025, windows-11-arm]
        node-version: [24.x]
    env: # Force Node.js 24 for all actions
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
        with:
          lfs: false

      - name: Fetch LFS objects
        run: |
          git lfs install
          git lfs pull

      - name: Install Windows SDK
        if: runner.os == 'Windows'
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v2.4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1

      - name: Install Electron binary
        if: runner.os == 'Windows'
        run: |
          Remove-Item -Recurse -Force node_modules/electron/dist -ErrorAction SilentlyContinue
          node node_modules/electron/install.js
        shell: pwsh

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: prepare-package
        run: npm run prepare-package

      - name: package arm64
        if: runner.arch == 'ARM64'
        run: npm run package -- --arm64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: package x64
        if: runner.arch == 'X64'
        run: npm run package -- --x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
