name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    permissions:
      contents: write
      discussions: write
      deployments: write
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-2025, ubuntu-24.04, ubuntu-24.04-arm ] # windows-11-arm removed because conflicting with x64

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: test
        run: npm run test

      - name: build
        run: npm run build

      - name: package
        run: npm run make

      - name: prepare-snap
        if: runner.os == 'Linux'
        run: npm run prepare-snap

      - name: build linux snap
        if: runner.os == 'Linux'
        uses: snapcore/action-build@v1
        id: build
        with:
          snapcraft-channel: '8.x'

      - name: publish to snap store
        uses: snapcore/action-publish@v1
        if: runner.os == 'Linux'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            out/make/**/RELEASES
            out/make/**/*.exe
            out/make/**/*.nupkg
            out/make/**/*.zip
            out/make/**/*.dmg
            out/make/**/*.AppImage
            **/*.snap
            out/make/**/*.deb
            out/make/**/*.rpm
            out/make/**/*.tar.gz
            out/make/**/*.yml
            out/make/**/*.blockmap
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
