name: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    permissions:
      contents: write
      discussions: write
      deployments: write
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install


      - name: build
        run: npm run publish

      - name: test
        run: npm run test

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            out/make/**/RELEASES
            out/make/**/*.exe
            out/make/**/*.nupkg
            out/make/**/*.zip
            out/make/**/*.dmg
            out/make/**/*.AppImage
            out/make/**/*.snap
            out/make/**/*.deb
            out/make/**/*.rpm
            out/make/**/*.tar.gz
            out/make/**/*.yml
            out/make/**/*.blockmap
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
