name: Build/release Smart Video Processor

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    permissions:
      deployments: write
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run make

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run make

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run make

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            out/make/**/*.exe
            out/make/**/*.zip
            out/make/**/*.dmg
            out/make/**/*.AppImage
            out/make/**/*.snap
            out/make/**/*.deb
            out/make/**/*.rpm
            out/make/**/*.tar.gz
            out/make/**/*.yml
            out/make/**/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
